name: api-ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: ping
        run: echo "workflow syntax OK"

      - name: checkout
        uses: actions/checkout@v4

      - name: compute-owner
        id: names
        run: |
          owner_lc="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          echo "owner_lc=$owner_lc" >> "$GITHUB_OUTPUT"

      - name: ghcr-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build-push-image
        uses: docker/build-push-action@v6
        with:
          context: ./Motoscope/motoscope-api
          file: ./Motoscope/motoscope-api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.names.outputs.owner_lc }}/motoscope-api:latest
            ghcr.io/${{ steps.names.outputs.owner_lc }}/motoscope-api:${{ github.sha }}

      - name: ssh-ensure-stack
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_API }}
          username: ${{ secrets.SSH_USER_API }}
          key: ${{ secrets.SSH_KEY_API }}
          port: ${{ secrets.SSH_PORT_API }}
          script: |
            set -euo pipefail
            owner_lc=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            image="ghcr.io/${owner_lc}/motoscope-api:latest"
            # docker login ghcr.io -u "${owner_lc}" -p "${{ secrets.GHCR_PAT }}" # if package private
            docker pull "$image"
            cd /srv/motoscope-api/Motoscope/motoscope-api
            docker-compose -p motoscope-api up -d
