name: api-ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: ping
        run: echo "workflow syntax OK"

      - name: checkout
        uses: actions/checkout@v4

      - name: compute-owner
        id: names
        run: |
          owner_lc="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          echo "owner_lc=$owner_lc" >> "$GITHUB_OUTPUT"

      # login with PAT
      - name: ghcr-login-with-pat
        run: |
          echo "${{ secrets.GHCR_PAT_API }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin

      # build & push
      - name: build-push-image
        uses: docker/build-push-action@v6
        with:
          context: ./Motoscope/motoscope-api
          file: ./Motoscope/motoscope-api/Dockerfile
          push: true
          provenance: false
          tags: |
            ghcr.io/${{ secrets.GHCR_USER }}/motoscope-api:latest
            ghcr.io/${{ secrets.GHCR_USER }}/motoscope-api:${{ github.sha }}
          outputs: type=registry


      - name: ssh-ensure-stack
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_API }}
          username: ${{ secrets.SSH_USER_API }}
          key: ${{ secrets.SSH_KEY_API }}
          port: ${{ secrets.SSH_PORT_API }}
          script: |
            set -euo pipefail

            # login to GHCR if package is private
            echo "${{ secrets.GHCR_PAT_API }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin || true

            image="ghcr.io/${{ secrets.GHCR_USER }}/motoscope-api:latest"
            docker pull "$image"

            cd /srv/motoscope-api/Motoscope/motoscope-api

            if docker compose version >/dev/null 2>&1; then
              COMPOSE="docker compose"
            else
              COMPOSE="docker-compose"
            fi
            echo "Using: $COMPOSE"

            # stop old stack and remove the old buggy containers
            $COMPOSE -p motoscope-api down || true
            docker rm -f motoscope-api_db_1 motoscope-api 2>/dev/null || true

            # bring everything back up clean
            $COMPOSE -p motoscope-api up -d --remove-orphans --force-recreate

            # quick health check
            sleep 2
            docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"


      - name: ssh-prepare-dirs
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_API }}
          username: ${{ secrets.SSH_USER_API }}
          key: ${{ secrets.SSH_KEY_API }}
          port: ${{ secrets.SSH_PORT_API }}
          script: |
            set -euo pipefail
            mkdir -p /srv/motoscope-api/Motoscope/motoscope-api/{migrations,seeds,ops}

      - name: scp-upload-sql
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_API }}
          username: ${{ secrets.SSH_USER_API }}
          key: ${{ secrets.SSH_KEY_API }}
          port: ${{ secrets.SSH_PORT_API }}
          source: "Motoscope/motoscope-api/schema.sql,Motoscope/motoscope-api/migrations/*,Motoscope/motoscope-api/seeds/*"
          target: "/srv/motoscope-api/Motoscope/motoscope-api/"

      - name: ssh-run-migrations
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_API }}
          username: ${{ secrets.SSH_USER_API }}
          key: ${{ secrets.SSH_KEY_API }}
          port: ${{ secrets.SSH_PORT_API }}
          script: |
            script: |
              set -euo pipefail
              echo "${{ secrets.GHCR_PAT_API }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
              image="ghcr.io/${{ secrets.GHCR_USER }}/motoscope-api:latest"
              docker pull "$image"
              cd /srv/motoscope-api/Motoscope/motoscope-api
              docker-compose -p motoscope-api up -d

