name: Build & Deploy Motoscope API (GHCR)
on:
  push:
    branches: [ "main" ]
    paths:
      - "Motoscope/motoscope-api/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./Motoscope/motoscope-api
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/motoscope-api:latest
            ghcr.io/${{ github.repository_owner }}/motoscope-api:${{ github.sha }}

      - name: SSH & update container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository_owner }}/motoscope-api:latest
            cd /srv/motoscope-api/Motoscope/motoscope-api
            docker compose up -d
            docker image prune -f
