name: Build & Deploy Motoscope API (GHCR)

on:
  push:
    branches: [ "main" ]
    paths:
      - "Motoscope/motoscope-api/**"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_BASENAME: motoscope-api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute lowercase owner
        id: names
        run: |
          owner_lc="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          echo "owner_lc=$owner_lc" >> $GITHUB_OUTPUT

      - name: Log in to GHCR (runner)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./Motoscope/motoscope-api
          file: ./Motoscope/motoscope-api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.names.outputs.owner_lc }}/${{ env.IMAGE_BASENAME }}:latest
            ghcr.io/${{ steps.names.outputs.owner_lc }}/${{ env.IMAGE_BASENAME }}:${{ github.sha }}

      - name: SSH & update container on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_API }}
          username: ${{ secrets.SSH_USER_API }}     # deploy
          key: ${{ secrets.SSH_KEY_API }}           # deploy’s PRIVATE key
          port: ${{ secrets.SSH_PORT_API }}
          script: |
            set -euo pipefail
            owner_lc=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            image="ghcr.io/${owner_lc}/${{ env.IMAGE_BASENAME }}:latest"

            # If package is private, login with PAT
            if [ -n "${{ secrets.GHCR_PAT }}" ]; then
              docker login ghcr.io -u "${owner_lc}" -p "${{ secrets.GHCR_PAT }}"
            fi

            docker pull "$image"

            cd /srv/motoscope-api/Motoscope/motoscope-api
            docker compose up -d --remove-orphans
            docker image prune -f

      - name: Upload migrations & seeds & schema to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_API }}
          username: ${{ secrets.SSH_USER_API }}   # deploy
          key: ${{ secrets.SSH_KEY_API }}         # deploy's PRIVATE key
          port: ${{ secrets.SSH_PORT_API }}
          source: "Motoscope/motoscope-api/migrations/*,Motoscope/motoscope-api/seeds/*,Motoscope/motoscope-api/schema.sql,Motoscope/motoscope-api/ops/migrate.sh"
          target: "/srv/motoscope-api/Motoscope/motoscope-api/"

      - name: Run DB migrations on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_API }}
          username: ${{ secrets.SSH_USER_API }}
          key: ${{ secrets.SSH_KEY_API }}
          port: ${{ secrets.SSH_PORT_API }}
          script: |
            set -euo pipefail
            cd /srv/motoscope-api/Motoscope/motoscope-api
            chmod +x ops/migrate.sh
            ./ops/migrate.sh



